openapi: 3.0.0
info:
  title: GovSignal Scout API
  version: 1.1.0 # Bump version to show maturity
  description: |
    Internal API for inter-agent communication. 
    Compliance: NIST SP 800-171 (Access Control).

paths:
  /signals:
    get:
      summary: Retrieve procurement signals
      security:
        - BearerAuth: [] # Explicitly define security
      parameters:
        - in: header
          name: X-Audit-Trace-ID
          schema:
            type: string
            format: uuid
          required: true
          description: Traceability token for SOX/ITAR compliance logs.
      responses:
        '200':
          description: List of active signals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Signal'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Signal:
      type: object
      properties:
        signal_id:
          type: string
          format: uuid
        target_category:
          type: string
          example: "Semiconductors"
        source:
          type: string
          example: "SAM.gov"
        title:
          type: string
        url:
          type: string
          format: uri
        demand_probability:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
        erp_action_recommendation:
          type: string
          enum: [monitor, flag_for_review, release_capital_hold]
        timestamp:
          type: string
          format: date-time
        risk_metadata: # Add this to match the "Risk" narrative
          type: object
          properties:
            criticality_score:
              type: number
            defense_industrial_base_impact:
              type: boolean
